repos:
  - repo: local
    hooks:
      - id: isort
        name: isort --settings-file black_isort_flake8_pre-commit/.isort.cfg
        entry: isort
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black --config black_isort_flake8_pre-commit/.black
        entry: black
        language: system
        exclude: ".pre-commit-config.yaml"

      - id: flake8
        name: flake8
        entry: flake8 --config black_isort_flake8_pre-commit/.flake8
        language: system
        types: [python]
        pass_filenames: false